### ISSUE TITLE
Fix broken link of license badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/gitifyme#28]
IN readme file https://raw.githubusercontent.com/arshadkazmi42/gitifyme/master/README.md

The link to license badge is broken https://github.com/arshadkazmi42/gitifyme/LICENSE

This needs to be changed to https://github.com/arshadkazmi42/gitifyme/blob/master/LICENSE

**Comment by Safirangi** [comment]
I would like to work on this issue
